import type { ComputeProviderDefinition } from "./ComputeConnectionContracts";

export const COMPUTE_PROVIDER_CATALOG: ComputeProviderDefinition[] = [
  {
    providerId: "notebook_kaggle",
    providerFamily: "NOTEBOOK",
    displayName: "Kaggle",
    authMethod: "CREDENTIAL_BUNDLE",
    credentialKeys: ["KAGGLE_USERNAME", "KAGGLE_KEY"],
    configurableKeys: [],
    roles: ["BASIC", "ADMIN"],
    implemented: true,
    description: "Kaggle notebook/kernel execution.",
  },
  {
    providerId: "notebook_colab",
    providerFamily: "NOTEBOOK",
    displayName: "Google Colab",
    authMethod: "TOKEN",
    credentialKeys: ["COLAB_ACCESS_TOKEN"],
    configurableKeys: [],
    roles: ["BASIC", "ADMIN"],
    implemented: true,
    description: "Colab runtime control API.",
  },
  {
    providerId: "notebook_paperspace",
    providerFamily: "NOTEBOOK",
    displayName: "Paperspace",
    authMethod: "CREDENTIAL_BUNDLE",
    credentialKeys: [
      "PAPERSPACE_API_KEY",
      "PAPERSPACE_TEMPLATE_ID",
      "PAPERSPACE_MACHINE_TYPE",
      "PAPERSPACE_REGION",
    ],
    configurableKeys: [
      "PAPERSPACE_DISK_GB",
      "PAPERSPACE_STARTUP_SCRIPT_ID",
    ],
    roles: ["BASIC", "ADMIN"],
    implemented: true,
    description: "Paperspace machine-backed notebook.",
  },
  {
    providerId: "notebook_lightning",
    providerFamily: "NOTEBOOK",
    displayName: "Lightning AI",
    authMethod: "CREDENTIAL_BUNDLE",
    credentialKeys: ["LIGHTNING_USER_ID", "LIGHTNING_API_KEY"],
    configurableKeys: ["LIGHTNING_MACHINE", "LIGHTNING_PYTHON"],
    roles: ["BASIC", "ADMIN"],
    implemented: true,
    description: "Lightning Studio execution.",
  },
  {
    providerId: "notebook_hf_zerogpu",
    providerFamily: "NOTEBOOK",
    displayName: "Hugging Face ZeroGPU",
    authMethod: "CREDENTIAL_BUNDLE",
    credentialKeys: ["HF_ZEROGPU_SPACE", "HF_ZEROGPU_API_NAME"],
    configurableKeys: ["HF_TOKEN"],
    roles: ["BASIC", "ADMIN"],
    implemented: true,
    description: "Hugging Face Space hosted GPU function.",
  },
  {
    providerId: "sandbox_pandastack_hosted",
    providerFamily: "SANDBOX",
    displayName: "PandaStack Hosted",
    authMethod: "API_KEY",
    credentialKeys: ["PANDASTACK_API_KEY"],
    configurableKeys: [],
    roles: ["ADMIN"],
    implemented: true,
    description: "Hosted sandbox execution backend for admin-only isolated workloads.",
  },
  {
    providerId: "sandbox_vibengine",
    providerFamily: "SANDBOX",
    displayName: "Vibengine",
    authMethod: "API_KEY",
    credentialKeys: ["VIBENGINE_API_KEY"],
    configurableKeys: [],
    roles: ["ADMIN"],
    implemented: false,
    description: "Hosted sandbox backend; admin-only in v1 until the real adapter is wired.",
  },
  {
    providerId: "sandbox_instavm",
    providerFamily: "SANDBOX",
    displayName: "InstaVM",
    authMethod: "API_KEY",
    credentialKeys: ["INSTAVM_API_KEY"],
    configurableKeys: [],
    roles: ["ADMIN"],
    implemented: false,
    description: "Hosted microVM backend; admin-only in v1 until the real adapter is wired.",
  },
  {
    providerId: "sandbox_leap0",
    providerFamily: "SANDBOX",
    displayName: "Leap0",
    authMethod: "API_KEY",
    credentialKeys: ["LEAP0_API_KEY"],
    configurableKeys: [],
    roles: ["ADMIN"],
    implemented: false,
    description: "Hosted Firecracker sandbox backend; admin-only in v1 until the real adapter is wired.",
  },
  {
    providerId: "sandbox_blaxel",
    providerFamily: "SANDBOX",
    displayName: "Blaxel",
    authMethod: "API_KEY",
    credentialKeys: ["BLAXEL_API_KEY"],
    configurableKeys: [],
    roles: ["ADMIN"],
    implemented: false,
    description: "Hosted persistent sandbox backend; admin-only in v1 until the real adapter is wired.",
  },
  {
    providerId: "sandbox_opencomputer",
    providerFamily: "SANDBOX",
    displayName: "OpenComputer",
    authMethod: "API_KEY",
    credentialKeys: ["OPENCOMPUTER_API_KEY"],
    configurableKeys: [],
    roles: ["ADMIN"],
    implemented: false,
    description: "Hosted Linux sandbox backend; admin-only in v1 until the real adapter is wired.",
  },
  {
    providerId: "sandbox_freestyle",
    providerFamily: "SANDBOX",
    displayName: "Freestyle VMs",
    authMethod: "API_KEY",
    credentialKeys: ["FREESTYLE_API_KEY"],
    configurableKeys: [],
    roles: ["ADMIN"],
    implemented: false,
    description: "Hosted VM backend; admin-only in v1 until the real adapter is wired.",
  },
  {
    providerId: "sandbox_runloop",
    providerFamily: "SANDBOX",
    displayName: "Runloop",
    authMethod: "API_KEY",
    credentialKeys: ["RUNLOOP_API_KEY"],
    configurableKeys: [],
    roles: ["ADMIN"],
    implemented: false,
    description: "Hosted devbox sandbox backend; admin-only in v1 until the real adapter is wired.",
  },
  {
    providerId: "sandbox_temps",
    providerFamily: "SANDBOX",
    displayName: "Temps",
    authMethod: "API_KEY",
    credentialKeys: ["TEMPS_API_KEY"],
    configurableKeys: [],
    roles: ["ADMIN"],
    implemented: false,
    description: "Container/microVM backend; admin-only in v1 until the real adapter is wired.",
  },
  {
    providerId: "api_vast",
    providerFamily: "API_GPU",
    displayName: "Vast.ai",
    authMethod: "API_KEY",
    credentialKeys: ["VAST_API_KEY"],
    configurableKeys: ["VAST_API_BASE_URL"],
    roles: ["ADMIN"],
    implemented: false,
    description: "Remote GPU API provider; admin-only in v1.",
  },
  {
    providerId: "api_runpod_v2",
    providerFamily: "API_GPU",
    displayName: "RunPod",
    authMethod: "API_KEY",
    credentialKeys: ["RUNPOD_API_KEY"],
    configurableKeys: ["RUNPOD_API_BASE_URL"],
    roles: ["ADMIN"],
    implemented: false,
    description: "Remote GPU API provider; admin-only in v1.",
  },
  {
    providerId: "api_daytona",
    providerFamily: "API_GPU",
    displayName: "Daytona",
    authMethod: "API_KEY",
    credentialKeys: ["DAYTONA_API_KEY"],
    configurableKeys: ["DAYTONA_API_BASE_URL"],
    roles: ["ADMIN"],
    implemented: false,
    description: "Remote sandbox/GPU control API; admin-only in v1.",
  },
  {
    providerId: "api_paperspace",
    providerFamily: "API_GPU",
    displayName: "Paperspace API",
    authMethod: "API_KEY",
    credentialKeys: ["PAPERSPACE_API_KEY"],
    configurableKeys: ["PAPERSPACE_API_BASE_URL"],
    roles: ["ADMIN"],
    implemented: false,
    description: "Remote machine control API; admin-only in v1.",
  },
  {
    providerId: "api_modal",
    providerFamily: "API_GPU",
    displayName: "Modal",
    authMethod: "API_KEY",
    credentialKeys: ["MODAL_TOKEN_ID", "MODAL_TOKEN_SECRET"],
    configurableKeys: [],
    roles: ["ADMIN"],
    implemented: false,
    description: "Remote compute control API; admin-only in v1.",
  },
];

export function getComputeProviderDefinition(
  providerId: string,
): ComputeProviderDefinition | undefined {
  return COMPUTE_PROVIDER_CATALOG.find((provider) => provider.providerId === providerId);
}