import type { ComputeProviderDefinition } from "./ComputeConnectionContracts";

export const COMPUTE_PROVIDER_CATALOG: ComputeProviderDefinition[] = [
  {
    providerId: "notebook_kaggle",
    providerFamily: "NOTEBOOK",
    displayName: "Kaggle",
    authMethod: "CREDENTIAL_BUNDLE",
    credentialKeys: ["KAGGLE_USERNAME", "KAGGLE_KEY"],
    configurableKeys: [],
    roles: ["BASIC", "ADMIN"],
    implemented: true,
    description: "Kaggle notebook/kernel execution.",
  },
  {
    providerId: "notebook_colab",
    providerFamily: "NOTEBOOK",
    displayName: "Google Colab",
    authMethod: "TOKEN",
    credentialKeys: ["COLAB_ACCESS_TOKEN"],
    configurableKeys: [],
    roles: ["BASIC", "ADMIN"],
    implemented: true,
    description: "Colab runtime control API.",
  },
  {
    providerId: "notebook_paperspace",
    providerFamily: "NOTEBOOK",
    displayName: "Paperspace",
    authMethod: "CREDENTIAL_BUNDLE",
    credentialKeys: [
      "PAPERSPACE_API_KEY",
      "PAPERSPACE_TEMPLATE_ID",
      "PAPERSPACE_MACHINE_TYPE",
      "PAPERSPACE_REGION",
    ],
    configurableKeys: [
      "PAPERSPACE_DISK_GB",
      "PAPERSPACE_STARTUP_SCRIPT_ID",
    ],
    roles: ["BASIC", "ADMIN"],
    implemented: true,
    description: "Paperspace machine-backed notebook.",
  },
  {
    providerId: "notebook_lightning",
    providerFamily: "NOTEBOOK",
    displayName: "Lightning AI",
    authMethod: "CREDENTIAL_BUNDLE",
    credentialKeys: ["LIGHTNING_USER_ID", "LIGHTNING_API_KEY"],
    configurableKeys: ["LIGHTNING_MACHINE", "LIGHTNING_PYTHON"],
    roles: ["BASIC", "ADMIN"],
    implemented: true,
    description: "Lightning Studio execution.",
  },
  {
    providerId: "notebook_hf_zerogpu",
    providerFamily: "NOTEBOOK",
    displayName: "Hugging Face ZeroGPU",
    authMethod: "CREDENTIAL_BUNDLE",
    credentialKeys: ["HF_ZEROGPU_SPACE", "HF_ZEROGPU_API_NAME"],
    configurableKeys: ["HF_TOKEN"],
    roles: ["BASIC", "ADMIN"],
    implemented: true,
    description: "Hugging Face Space hosted GPU function.",
  },
  {
    providerId: "api_vast",
    providerFamily: "API_GPU",
    displayName: "Vast.ai",
    authMethod: "API_KEY",
    credentialKeys: ["VAST_API_KEY"],
    configurableKeys: ["VAST_API_BASE_URL"],
    roles: ["ADMIN"],
    implemented: false,
    description: "Remote GPU API provider; admin-only in v1.",
  },
  {
    providerId: "api_runpod_v2",
    providerFamily: "API_GPU",
    displayName: "RunPod",
    authMethod: "API_KEY",
    credentialKeys: ["RUNPOD_API_KEY"],
    configurableKeys: ["RUNPOD_API_BASE_URL"],
    roles: ["ADMIN"],
    implemented: false,
    description: "Remote GPU API provider; admin-only in v1.",
  },
  {
    providerId: "api_daytona",
    providerFamily: "API_GPU",
    displayName: "Daytona",
    authMethod: "API_KEY",
    credentialKeys: ["DAYTONA_API_KEY"],
    configurableKeys: ["DAYTONA_API_BASE_URL"],
    roles: ["ADMIN"],
    implemented: false,
    description: "Remote sandbox/GPU control API; admin-only in v1.",
  },
  {
    providerId: "api_paperspace",
    providerFamily: "API_GPU",
    displayName: "Paperspace API",
    authMethod: "API_KEY",
    credentialKeys: ["PAPERSPACE_API_KEY"],
    configurableKeys: ["PAPERSPACE_API_BASE_URL"],
    roles: ["ADMIN"],
    implemented: false,
    description: "Remote machine control API; admin-only in v1.",
  },
  {
    providerId: "api_modal",
    providerFamily: "API_GPU",
    displayName: "Modal",
    authMethod: "API_KEY",
    credentialKeys: ["MODAL_TOKEN_ID", "MODAL_TOKEN_SECRET"],
    configurableKeys: [],
    roles: ["ADMIN"],
    implemented: false,
    description: "Remote compute control API; admin-only in v1.",
  },
];

export function getComputeProviderDefinition(
  providerId: string,
): ComputeProviderDefinition | undefined {
  return COMPUTE_PROVIDER_CATALOG.find((provider) => provider.providerId === providerId);
}
