/**
 * ShortForge / FactoryOS — Structural Intelligence Contracts
 * Provides normalized types for codebase AST structure generated by Graphify.
 */

export type EdgeConfidence = "EXTRACTED" | "INFERRED" | "UNKNOWN";

export interface StructuralNode {
  readonly id: string;
  readonly label: string;
  readonly type: string;
  readonly sourceFile?: string;
  readonly sourceLocation?: string;
  readonly community?: number;
  readonly isCallable?: boolean;
  readonly properties?: Record<string, unknown>;
}

export interface StructuralEdge {
  readonly id: string;
  readonly sourceId: string;
  readonly targetId: string;
  readonly relation: string;
  readonly confidence: EdgeConfidence;
  readonly confidenceScore?: number;
  readonly sourceFile?: string;
  readonly sourceLocation?: string;
  readonly weight?: number;
  readonly properties?: Record<string, unknown>;
}

export interface StructuralGraphStats {
  readonly nodeCount: number;
  readonly edgeCount: number;
  readonly extractedEdgesCount: number;
  readonly inferredEdgesCount: number;
  readonly communityCount: number;
  readonly snapshotId?: string;
  readonly graphifyVersion?: string;
  readonly sourceCommit?: string;
  readonly dirtyWorktree?: boolean;
}

export interface GraphValidationReport {
  readonly valid: boolean;
  readonly totalNodes: number;
  readonly totalEdges: number;
  readonly danglingEdgeCount: number;
  readonly extractedCount: number;
  readonly inferredCount: number;
  readonly unknownConfidenceCount?: number;
  readonly errors: string[];
}

export interface IStructuralGraphProvider {
  getNode(id: string): StructuralNode | null;
  searchNodes(query: string, limit?: number): StructuralNode[];
  getNeighbors(nodeId: string, direction?: "in" | "out" | "both"): StructuralNode[];
  getEdges(nodeId: string, direction?: "in" | "out" | "both"): StructuralEdge[];
  findDependents(nodeId: string): StructuralNode[];
  findDependencies(nodeId: string): StructuralNode[];
  findPath(startId: string, targetId: string, maxDepth?: number): StructuralNode[] | null;
  getStats(): StructuralGraphStats;
  validate(): GraphValidationReport;
}
