import { afterEach, describe, expect, it, vi } from "vitest";
import {
  ArcmiraVideoProvider,
  TranscriptYTProvider,
  TubeToTranscriptProvider,
  VidWordsProvider,
  YouTubeDataApiProvider,
} from "./VideoResearchProviders";
import { VideoResearchRouter } from "./VideoResearchRouter";

afterEach(() => {
  vi.unstubAllGlobals();
  vi.unstubAllEnvs();
});

describe("video research providers", () => {
  it("normalizes Arcmira timestamped transcript lines", async () => {
    vi.stubEnv("ARCMIRA_API_KEY", "arcmira-test");
    vi.stubGlobal(
      "fetch",
      vi.fn(async (url: string | URL) => {
        expect(String(url)).toContain("/v1/transcripts/");
        return new Response(
          JSON.stringify({
            video: {
              id: "abc12345678",
              title: "Example",
              channel: "Research Channel",
              watchUrl: "https://www.youtube.com/watch?v=abc12345678",
            },
            language: "en",
            source: "captions",
            autoGenerated: true,
            lines: [
              { start: 1, end: 3, text: "first line" },
              { start: 3, end: 5, text: "second line" },
            ],
          }),
          { status: 200 },
        );
      }),
    );

    const result = await new ArcmiraVideoProvider().transcript(
      "https://youtu.be/abc12345678",
    );

    expect(result.videoId).toBe("abc12345678");
    expect(result.segments).toHaveLength(2);
    expect(result.sourceKind).toBe("AUTO_CAPTIONS");
  });

  it("normalizes TranscriptYT JSON segments", async () => {
    vi.stubEnv("TRANSCRIPT_YT_API_KEY", "transcriptyt-test");
    vi.stubGlobal(
      "fetch",
      vi.fn(async (url: string | URL) => {
        expect(String(url)).toContain("/v1/transcript");
        return new Response(
          JSON.stringify({
            videoId: "abc12345678",
            title: "Example",
            author: "Ada",
            language: "en",
            translated: false,
            autoGenerated: false,
            source: "captions",
            durationSeconds: 10,
            segments: [
              { start: 0, duration: 2, text: "hello" },
              { start: 2, duration: 2, text: "world" },
            ],
            text: "hello world",
          }),
          { status: 200 },
        );
      }),
    );

    const result = await new TranscriptYTProvider().transcript(
      "abc12345678",
    );
    expect(result.text).toBe("hello world");
    expect(result.segments[1].startSeconds).toBe(2);
  });

  it("normalizes VidWords Basic-auth transcript payloads", async () => {
    vi.stubEnv("VIDWORDS_API_KEY", "vidwords-test");
    const fetchMock = vi.fn(async (_url: string | URL, init?: RequestInit) => {
      expect(new Headers(init?.headers).get("Authorization")).toBe(
        "Basic vidwords-test",
      );
      return new Response(
        JSON.stringify({
          results: [{
            id: "abc12345678",
            title: "Example",
            text: "hello world",
            segments: [{ start: 0, duration: 2, text: "hello world" }],
          }],
        }),
        { status: 200 },
      );
    });
    vi.stubGlobal("fetch", fetchMock);

    const result = await new VidWordsProvider().transcript(
      "abc12345678",
    );
    expect(result.text).toBe("hello world");
  });

  it("normalizes TubeToTranscript and preserves metadata", async () => {
    vi.stubEnv("TUBETOTRANSCRIPT_API_KEY", "tube-test");
    vi.stubGlobal(
      "fetch",
      vi.fn(async () =>
        new Response(
          JSON.stringify({
            language: "en",
            is_generated: false,
            length_seconds: 5,
            metadata: {
              videoId: "abc12345678",
              title: "Example",
              channel: "Ada",
            },
            transcript: [
              { text: "hello", start: 0, duration: 2 },
              { text: "world", start: 2, duration: 3 },
            ],
            text: "hello world",
          }),
          { status: 200 },
        ),
      ),
    );

    const result = await new TubeToTranscriptProvider().transcript(
      "abc12345678",
    );
    expect(result.channel).toBe("Ada");
    expect(result.durationSeconds).toBe(5);
  });

  it("uses YouTube Data API for metadata search only", async () => {
    vi.stubEnv("YOUTUBE_API_KEY", "youtube-test");
    vi.stubGlobal(
      "fetch",
      vi.fn(async (url: string | URL) => {
        expect(String(url)).toContain("/youtube/v3/search");
        expect(String(url)).toContain("type=video");
        return new Response(
          JSON.stringify({
            items: [{
              id: { videoId: "abc12345678" },
              snippet: {
                title: "Example video",
                channelTitle: "Ada",
                channelId: "channel1",
                description: "description",
              },
            }],
          }),
          { status: 200 },
        );
      }),
    );

    const [result] = await new YouTubeDataApiProvider().search(
      "example",
      1,
    );
    expect(result.videoId).toBe("abc12345678");
    expect(result.channel).toBe("Ada");
  });

  it("falls back to the next transcript provider", async () => {
    const providerA: any = {
      id: "a",
      capabilities: ["TRANSCRIPT"],
      health: async () => true,
      transcript: async () => {
        throw new Error("first provider down");
      },
      search: async () => [],
    };
    const providerB: any = {
      id: "b",
      capabilities: ["TRANSCRIPT"],
      health: async () => true,
      transcript: async () => ({
        providerId: "b",
        videoId: "abc12345678",
        sourceUrl: "https://www.youtube.com/watch?v=abc12345678",
        sourceKind: "CREATOR_CAPTIONS",
        segments: [],
        text: "ok",
        retrievedAt: new Date().toISOString(),
      }),
      search: async () => [],
    };

    const router = new VideoResearchRouter({
      providers: [providerA, providerB],
      transcriptOrder: ["a", "b"],
    });

    const result = await router.transcript("abc12345678");
    expect(result.providerId).toBe("b");
  });

  it("fails closed when credentials are absent", async () => {
    expect(await new YouTubeDataApiProvider().search("test", 2)).toEqual([]);
    await expect(
      new TranscriptYTProvider().transcript("abc12345678"),
    ).rejects.toThrow(/TRANSCRIPT_YT_API_KEY/);
  });
});
