/**
 * FactoryOS Frontier v3 — Evolution Brain Seam
 * Strictly isolated observation, analysis, and proposal seam.
 * Enforces that NO self-modifying mutation enters production without human/canary approval.
 */

export interface EvolutionProposal {
  readonly proposalId: string;
  readonly targetSubsystem: "PROMPT" | "ROUTING" | "FLOOR_POLICY" | "CODE";
  readonly rationale: string;
  readonly proposedChange: Record<string, unknown>;
  readonly benchmarkComparison: {
    readonly baselineQuality: number;
    readonly simulatedQuality: number;
    readonly deltaPct: number;
  };
  readonly status: "PROPOSED" | "CANARY_TESTING" | "APPROVED" | "REJECTED" | "ROLLED_BACK";
  readonly createdAt: string;
  readonly reviewedAt?: string;
  readonly reviewedBy?: string;
}

export class EvolutionBrainSeam {
  private proposals: Map<string, EvolutionProposal> = new Map();

  /**
   * Records an improvement proposal generated by observing factory operations.
   */
  submitProposal(proposal: Omit<EvolutionProposal, "status" | "createdAt">): EvolutionProposal {
    const fullProposal: EvolutionProposal = {
      ...proposal,
      status: "PROPOSED",
      createdAt: new Date().toISOString(),
    };
    this.proposals.set(fullProposal.proposalId, fullProposal);
    return fullProposal;
  }

  /**
   * Promotes proposal to canary testing only under explicit approval.
   */
  promoteToCanary(proposalId: string, reviewer: string): EvolutionProposal {
    const p = this.proposals.get(proposalId);
    if (!p) throw new Error(`Proposal ${proposalId} not found`);
    const updated: EvolutionProposal = {
      ...p,
      status: "CANARY_TESTING",
      reviewedAt: new Date().toISOString(),
      reviewedBy: reviewer,
    };
    this.proposals.set(proposalId, updated);
    return updated;
  }

  getProposals(): EvolutionProposal[] {
    return Array.from(this.proposals.values());
  }
}
