#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(process.argv[2] ?? "knowledge");
const output = path.join(root,"obsidian","generated","MEMORY_CATALOG.md");

function walk(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir,{withFileTypes:true})) {
    if ([".git",".obsidian","node_modules","generated"].includes(entry.name)) continue;
    const full = path.join(dir,entry.name);
    if (entry.isDirectory()) out.push(...walk(full));
    else if (entry.isFile() && entry.name.endsWith(".md")) out.push(full);
  }
  return out;
}

function meta(text) {
  if (!text.startsWith("---\n")) return {};
  const end = text.indexOf("\n---",4);
  if (end < 0) return {};
  const out = {};
  for (const line of text.slice(4,end).split(/\r?\n/)) {
    const m = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (m) out[m[1]] = m[2].trim().replace(/^["']|["']$/g,"");
  }
  return out;
}

fs.mkdirSync(path.dirname(output),{recursive:true});

const rows = walk(root).map((file) => {
  const rel = path.relative(root,file).replaceAll(path.sep,"/");
  const m = meta(fs.readFileSync(file,"utf8"));
  return {
    path:rel,
    title:m.title ?? path.basename(rel,".md"),
    type:m.type ?? "",
    lifecycle:m.sf_lifecycle ?? "",
    verification:m.sf_verification_state ?? "",
  };
}).sort((a,b)=>a.path.localeCompare(b.path));

const lines = [
  "# Generated Memory Catalog",
  "",
  "> Generated by tools/obsidian/build-catalog.mjs. Do not hand-edit.",
  "",
  "Generated: "+new Date().toISOString(),
  "",
  "| Path | Title | Type | Lifecycle | Verification |",
  "| --- | --- | --- | --- | --- |",
  ...rows.map(r=>"| ["+r.path+"]("+r.path+") | "+r.title.replaceAll("|","\\|")+" | "+r.type+" | "+r.lifecycle+" | "+r.verification+" |"),
  "",
];

fs.writeFileSync(output,lines.join("\n"));
console.log("Wrote "+output+" ("+rows.length+" notes).");
